### ISSUE TITLE
phikips.py start problem

### ISSUE THREAD

**Issue by borewicz9** [sembsa/PhilipsLEDBulb-homekit#1]
Hello,
sudo python philips.py
`Traceback (most recent call last):
  File "philips.py", line 1, in <module>
    import mirobo
ImportError: No module named mirobo
`
mirobo --info
`Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 7, in <module>
    from mirobo.vacuum_cli import cli
  File "/usr/local/lib/python3.5/dist-packages/mirobo/__init__.py", line 4, in <module>
    from mirobo.vacuum import Vacuum, VacuumException
  File "/usr/local/lib/python3.5/dist-packages/mirobo/vacuum.py", line 8, in <module>
    from .device import Device, DeviceException
  File "/usr/local/lib/python3.5/dist-packages/mirobo/device.py", line 42
    self.ip = 192.168.1.106
                      ^
SyntaxError: invalid syntax`

is there any solution ?

**Comment by sembsa** [comment]
first type `python -V` maybe you have two version python, try python3 philips.py
and second in file device.py change self.ip = 192.168.1.106 for self.ip = "192.168.1.106"
try now

**Comment by borewicz9** [comment]
python -V shows Python 2.7.13 but /usr/local/lib/python2.7 folders are empty.
Everything is in /usr/local/lib/python3.5
After change to "192.168.1.106"
python philips.py:
`Traceback (most recent call last):
  File "philips.py", line 1, in <module>
    import mirobo
ImportError: No module named mirobo
`

python3 philips.py:
`Skrypt sterowania Philips Xiaomi LED Bulb
Traceback (most recent call last):
  File "philips.py", line 74, in <module>
    client.connect("homekit.local", 1883, 60)
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 760, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 887, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.5/socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
`

**Comment by sembsa** [comment]
ok, you must run `python3 philips.py` in file [https://github.com/sembsa/PhilipsLEDBulb-homekit/blob/master/philips.py#L74](https://github.com/sembsa/PhilipsLEDBulb-homekit/blob/master/philips.py#L74) in 74 line change mqtt broker [https://github.com/mcollina/mosca](https://github.com/mcollina/mosca)

**Comment by sembsa** [comment]
if you install on local machine type localhost

**Comment by borewicz9** [comment]
So I should change line 74 to client.connect("homekit.localhost", 1883, 60) and instal Mosca Standalone ?

**Comment by sembsa** [comment]
yes, in this line change "homekit.localhost" for "localhost" and install on local machine Mosca Broker and run Mosca :)

**Comment by borewicz9** [comment]
I've change to localhost and my hostname - raspberrypi but without effect:
`root@raspberrypi:/home/pi/PhilipsLEDBulb-homekit-master# python3 philips.py
Skrypt sterowania Philips Xiaomi LED Bulb
Traceback (most recent call last):
  File "philips.py", line 74, in <module>
    client.connect("localhost", 1883, 60)
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 760, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 887, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
`

`root@raspberrypi:/home/pi/PhilipsLEDBulb-homekit-master# mosca -v | pino
       +++.+++:   ,+++    +++;   '+++    +++.
      ++.+++.++   ++.++  ++,'+  `+',++  ++,++
      +`  +,  +: .+  .+  +;  +; '+  '+  +`  +`
      +`  +.  +: ,+  `+  ++  +; '+  ;+  +   +.
      +`  +.  +: ,+  `+   +'    '+      +   +.
      +`  +.  +: ,+  `+   :+.   '+      +++++.
      +`  +.  +: ,+  `+    ++   '+      +++++.
      +`  +.  +: ,+  `+     ++  '+      +   +.
      +`  +.  +: ,+  `+  +:  +: '+  ;+  +   +.
      +`  +.  +: .+  .+  +;  +; '+  '+  +   +.
      +`  +.  +:  ++;++  ++'++   ++'+'  +   +.
      +`  +.  +:   +++    +++.   ,++'   +   +.
[2017-09-23T22:57:00.660Z] INFO (mosca/6852 on raspberrypi): server started
    mqtt: 1883`

**Comment by sembsa** [comment]
try `ping localhost` on raspberry and show me

**Comment by sembsa** [comment]
and you must first run mosca and second windows ssh run python with script

**Comment by sembsa** [comment]
best way for you work on pi login not root :)

**Comment by borewicz9** [comment]
OK, there is some progress

pi@raspberrypi:~ $ ping localhost
PING localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.238 ms
64 bytes from localhost (::1): icmp_seq=2 ttl=64 time=0.245 ms
64 bytes from localhost (::1): icmp_seq=3 ttl=64 time=0.252 ms
64 bytes from localhost (::1): icmp_seq=4 ttl=64 time=0.242 ms

Mosca:

[2017-09-23T23:08:37.138Z] INFO (mosca/7687 on raspberrypi): server started
    mqtt: 1883
[2017-09-23T23:09:58.904Z] INFO (mosca/7687 on raspberrypi): client connected
    client: ""
[2017-09-23T23:09:59.060Z] INFO (mosca/7687 on raspberrypi): subscribed to topic
    topic: "/home/setOn"
    qos: 0
    client: ""
[2017-09-23T23:09:59.182Z] INFO (mosca/7687 on raspberrypi): subscribed to topic
    topic: "/home/setB"
    qos: 0
    client: ""
[2017-09-23T23:09:59.216Z] INFO (mosca/7687 on raspberrypi): subscribed to topic
    topic: "/home/setColor"
    qos: 0
    client: ""


pi@raspberrypi:~/PhilipsLEDBulb-homekit-master $ sudo python3 philips.py

Skrypt sterowania Philips Xiaomi LED Bulb
Connect with result code: 0

**Comment by sembsa** [comment]
ok, now work :) now you must pusblish on topic "/home/setOn" "on"

**Comment by sembsa** [comment]
serach on google program for mqtt publish, connect to localhost mqtt broker and send of topic 
on /home/setOn, /home/setB, /home/setColor

**Comment by sembsa** [comment]
for macOS is good MQTTBox

**Comment by borewicz9** [comment]
I've just install MQTTBox from Windows Store at PC, can I connect raspberry or should I install linux version on raspberry ?

**Comment by sembsa** [comment]
run on windows, and write adres ip for raspberry pi

**Comment by sembsa** [comment]
you change token for bulb ?

**Comment by borewicz9** [comment]
[https://www.dropbox.com/s/bb40r1nfhdwvzp4/mqqttbox1.jpg?dl=0](url)

**Comment by sembsa** [comment]
payload `on`

**Comment by borewicz9** [comment]
I've setup token in Self.token = bytes.fromhex ("TOKEN HERE")

**Comment by sembsa** [comment]
good 👍

**Comment by sembsa** [comment]
sorry payload `1`

**Comment by borewicz9** [comment]
1
topic:/home/setOn, qos:0, retain:false

Bulb did't turn on

**Comment by borewicz9** [comment]
Script stop working, now bulb turn on :)

**Comment by borewicz9** [comment]
Now how to add it to iOS 'Home' app ?

**Comment by sembsa** [comment]
is work yes ? and test other topic :)

**Comment by sembsa** [comment]
use homekit2mqtt on github and set this topic :)

**Comment by borewicz9** [comment]
OK, thank You very much, now I can turn it on and off via MQTTBox app.
Next step - [https://github.com/hobbyquaker/homekit2mqtt/wiki](url) at the morning :)

PS. Stawiam piwo jak będziesz w Częstochowie :-)

**Comment by sembsa** [comment]
ok, If you have questions you have to write :)

P.S. Ok 👍

**Comment by sembsa** [comment]
Close
